--- #YAML:1.0
name:               Gtk2-OSXApplication
version:            0.03
abstract:           Perl extension for mac integration code GtkOSXApplication
author:
    - fam. Oesterholt <oesterholt@apple.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Gtk2:  1.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
